# Generated by Django 5.2 on 2025-04-25 03:08

import django.db.models.deletion
import gll_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallo',
            fields=[
                ('nroPlaca', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('fechaNac', models.DateField()),
                ('color', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=1)),
                ('tipoGallo', models.CharField(choices=[('DP', 'Gallo De Pelea'), ('PADRE', 'Gallo Padre'), ('MADRE', 'Gallina madre')], max_length=20)),
                ('observaciones', models.TextField()),
                ('nombre_img', models.ImageField(upload_to=gll_app.models.imagen_upload_path)),
                ('placaMadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='gll_app.gallo')),
                ('placaPadre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='gll_app.gallo')),
            ],
        ),
    ]
