# Generated by Django 5.2 on 2025-04-29 17:26

import django.db.models.deletion
import gll_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallo',
            name='sexo',
            field=models.CharField(choices=[('M', 'Macho'), ('H', 'Hembra')], max_length=1),
        ),
        migrations.CreateModel(
            name='Encuentro',
            fields=[
                ('idEncuentro', models.AutoField(primary_key=True, serialize=False)),
                ('fechaYHora', models.DateTimeField()),
                ('galpon1', models.CharField(max_length=100)),
                ('galpon2', models.CharField(max_length=100)),
                ('video', models.FileField(null=True, upload_to=gll_app.models.imagen_upload_path)),
                ('pactada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pago_juez', models.DecimalField(decimal_places=2, max_digits=10)),
                ('apuesta_general', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premio_mayor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('porcentaje_premio_mayor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('apuesta_por_fuera', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('idGanador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gll_app.gallo')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantesEnEncuentro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEncuentro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.encuentro')),
                ('idParticipante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gll_app.gallo')),
            ],
            options={
                'unique_together': {('idEncuentro', 'idParticipante')},
            },
        ),
    ]
