# Generated by Django 5.2 on 2025-05-18 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0002_duenoanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallo',
            name='nombreDuenoAnterior',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gll_app.duenoanterior'),
        ),
    ]
