# Generated by Django 5.2 on 2025-04-29 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0002_alter_gallo_sexo_encuentro_participantesenencuentro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuentro',
            old_name='idGanador',
            new_name='ganador',
        ),
    ]
