# Generated by Django 5.2 on 2025-05-18 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0003_alter_gallo_nombreduenoanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='pago_juez',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='encuentro',
            name='porcentaje_premio_mayor',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
