# Generated by Django 5.2 on 2025-05-01 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gll_app', '0003_alter_encuentro_apuesta_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuentro',
            name='apuesta_por_fuera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
